### ISSUE TITLE
Bug in latest ultimaker 3 firmware

### ISSUE THREAD

**Issue by acca84** [Ultimaker/Ultimaker3#4]
Hello
I think i have found a bug in latest UM3 firmware

If i start a print and cancel it from LCD menu, the print stops as excepted but the material is unloaded.
It occurs when printing with printhead number 2, i didn't try using printhead number 1

Do anyone has the same behaviour ?
Thanks

**Comment by ckielstra** [comment]
@acca84 Thank you for reporting this bug. I'm not aware this bug has been reported before, so it is a situation that happens with few people. Ultimaker recommends you to do prints with printhead 1 when possible, the left printhead is firmly attached and will give the most accurate print results.

Since sales of the UM3 printer stopped a few years ago, only bugs will be fixed that make it impossible to use the printer. This bug is annoying and we'd love to see it fixed, but given the limited resources we have it's not going to be fixed.
